services:
  mx-frontend:
    image: ghcr.io/minusxai/minusx-frontend-canary:latest
    platform: linux/amd64
    container_name: mx-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./static:/app/public/static
    environment:
      - NODE_ENV=production
      - BASE_DUCKDB_DATA_PATH=/app
      - ANALYTICS_DB_DIR=/app/data/analytics
      - DB_TYPE=postgres
    env_file:
      - ./frontend/.env
    networks:
      - minusx-network

networks:
  minusx-network:
    name: minusx-network
    driver: bridge
