"""Custom OpenAI types for flexible tool calling and message handling."""

from typing import List, Literal, Required, Tuple, TypeAlias, Union
from typing_extensions import TypedDict
from openai.types.chat import (
    ChatCompletionAssistantMessageParam,
    ChatCompletionMessageToolCallParam,
    ChatCompletionSystemMessageParam,
    ChatCompletionUserMessageParam,
    ChatCompletionToolMessageParam,
    ChatCompletionFunctionMessageParam
)


class FunctionCallMX(TypedDict, total=False):
    """Extended function call with dict arguments."""
    arguments: Required[dict]
    """
    The arguments to call the function with. Always a dict (JSON object).
    HTTP response serialization handles converting to/from JSON strings.
    """

    name: Required[str]
    """The name of the function to call."""

    child_tasks_batch: List[List[dict]]
    """
    Child task results grouped by run_id (optional, runtime only, not persisted to log).
    Each inner list represents tasks that ran together (same run_id).
    Structure: [[{tool_call_id, agent, args, result}, ...], ...]
    """


class ChatCompletionMessageToolCallParamMX(ChatCompletionMessageToolCallParam):
    """Extended tool call param with flexible function arguments."""
    function: Required[FunctionCallMX]
    """The function that the model called."""


class ChatCompletionAssistantMessageParamMX(ChatCompletionAssistantMessageParam):
    """Extended assistant message param with custom tool calls."""
    tool_calls: List[ChatCompletionMessageToolCallParamMX]
    """The tool calls generated by the model, such as function calls."""


class ChatCompletionToolMessageParamMX(ChatCompletionToolMessageParam):
    """Extended tool message param that allows dict content."""
    content: Required[Union[str, dict]]
    """The contents of the tool message."""

    role: Required[Literal["tool"]]
    """The role of the messages author, in this case `tool`."""

    tool_call_id: Required[str]
    """Tool call that this message is responding to."""


# Type alias for completed tool calls (tool call + response pairs)
CompletedToolCallsMX = List[Tuple[ChatCompletionMessageToolCallParamMX, ChatCompletionToolMessageParamMX]]

class ChatCompletionToolMessageParamMXWithRunId(TypedDict, total=False):
    """Complete tool call representation with both call and response information."""
    content: Required[Union[str, dict]]
    """The contents of the tool message."""

    role: Required[Literal["tool"]]
    """The role of the messages author, in this case `tool`."""

    tool_call_id: Required[str]
    """Tool call that this message is responding to."""

    run_id: Required[str]
    """The run_id of the task that produced this result."""

    function: Required[FunctionCallMX]
    """The function that was called (includes name and arguments)."""

    created_at: Required[str]
    """ISO timestamp when the tool call was created."""

# Type alias for completed tool calls with run_id
CompletedToolCallsMXWithRunId = List[ChatCompletionToolMessageParamMXWithRunId]

# Union type for all message types with MX extensions
ChatCompletionMessageParamMX: TypeAlias = Union[
    ChatCompletionSystemMessageParam,
    ChatCompletionUserMessageParam,
    ChatCompletionAssistantMessageParamMX,
    ChatCompletionToolMessageParamMX,
    ChatCompletionFunctionMessageParam,
]
