import { createListenerMiddleware, isAnyOf } from '@reduxjs/toolkit';
import { IS_TEST } from '@/lib/constants';
import type { RootState, AppDispatch } from './store';
import {
  createConversation,
  sendMessage,
  retryConversationTurn,
  queueMessage,
  clearQueuedMessages,
  flushQueuedMessages,
  editAndForkMessage,
  updateConversation,
  completeToolCall,
  setError,
  selectConversation,
  selectAllToolsCompleted,
  addStreamingMessage,
  addAutoGeneratedMessages,
  clearStreamingContent,
  interruptChat,
  setUserInputResult,
  addUserInputRequest,
  loadConversation
} from './chatSlice';
import type { AutoGeneratedMessage } from './chatSlice';
import { selectAllowChatQueue, selectQueueStrategy } from './uiSlice';
import { UserInputException } from '@/lib/tools/user-input-exception';
import { generateUniqueId } from './id-generator';
import { captureError } from '@/lib/messaging/capture-error';
import { classifyErrorRetryability } from '@/lib/chat/error-retryability';
import { parsePiConversation } from '@/lib/conversations-utils';
import type { ConversationLog } from '@/orchestrator/types';
import type { AgentSkillSelection } from '@/lib/types';
import { API_BASE_URL, patchApiUrl } from './api-url';
import { runV3Turn, type V3TurnInput } from './conversation-stream-client';
import { ConversationsAPI } from '@/lib/data/conversations';
import { derivePendingToolCalls } from '@/lib/data/conversation-log';
import { collectToolCallMeta, piToolResultToStreamedCall, type ToolCallMeta } from '@/lib/chat/streamed-tool-calls';
import { withToolWatchdog } from './tool-watchdog';

// ---------------------------------------------------------------------------
// Synthetic skill-load events
// ---------------------------------------------------------------------------

/**
 * Compute the synthetic skill_load messages to emit for this turn, skipping any
 * skill that already has a skill_load message earlier in the conversation.
 *
 * Auto-injected system skills (e.g. `large_file`) are re-added to
 * `agent_args.skills.selected` on every turn while AppState stays large, so
 * without this dedup the UI would show a duplicate "Loaded skill X" chip per
 * turn. A skill loads once per conversation.
 */
export function computeSyntheticSkillLoads(
  selected: AgentSkillSelection[],
  existingMessages: ReadonlyArray<{ role: string; type?: string; content?: any }>,
  now: string,
): AutoGeneratedMessage[] {
  const alreadyLoaded = new Set(
    existingMessages
      .filter(m => m.role === 'autogenerated' && m.type === 'skill_load')
      .map(m => m.content?.name)
      .filter(Boolean),
  );
  return selected
    .filter(skill => skill.name && !alreadyLoaded.has(skill.name))
    .map(skill => ({
      role: 'autogenerated' as const,
      type: 'skill_load',
      content: { name: skill.name, source: skill.type },
      created_at: now,
    }));
}

/**
 * Push auto-generated skill_load messages into conv.messages for explicitly
 * selected skills (page-type preloads + user hash mentions).
 * These are UI-only and ignored by LLM message reconstruction.
 */
function emitSyntheticSkillLoads(
  conversationID: number,
  conversation: { agent_args?: any; messages?: ReadonlyArray<any> },
  dispatch: AppDispatch,
): void {
  const selected: AgentSkillSelection[] = conversation.agent_args?.skills?.selected ?? [];
  if (selected.length === 0) return;

  const messages = computeSyntheticSkillLoads(
    selected,
    conversation.messages ?? [],
    new Date().toISOString(),
  );
  if (messages.length === 0) return;

  dispatch(addAutoGeneratedMessages({ conversationID, messages }));
}

// AbortController registry for managing conversation interruption
// Key is conversation._id (stable internal ID that never changes)
// eslint-disable-next-line no-restricted-syntax -- client-side Redux listener; AbortControllers are ephemeral, no data leakage
const abortControllers = new Map<string, AbortController>();

// API base URL - defaults to relative path in browser, absolute in Node/tests
export const chatListenerMiddleware = createListenerMiddleware();

/**
 * Fire-and-forget post of a transport-level error to /api/chat/log-error so it
 * lands on the conversation document's `errors[]` and survives page reload.
 * Best-effort: any failure here is swallowed (we never recurse on log failures).
 */
function reportClientErrorToServer(
  conversationID: number,
  message: string,
  source: 'transport' | 'session' | 'unhandled' = 'transport',
  httpStatus?: number,
): void {
  if (!Number.isFinite(conversationID) || conversationID <= 0) return; // pre-init virtual id
  const body = {
    conversationID,
    error: {
      _type: 'error',
      source,
      message,
      timestamp: Date.now(),
      ...(typeof httpStatus === 'number' ? { details: { http_status: httpStatus } } : {}),
    },
  };
  void fetch(patchApiUrl(`${API_BASE_URL}/api/chat/log-error`), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  }).catch(() => { /* best-effort */ });
}

function classifyError(error: { name?: string; httpStatus?: number }): { source: 'transport' | 'session'; httpStatus?: number } {
  if (error?.name === 'SessionExpiredError' || error?.httpStatus === 401) {
    return { source: 'session', httpStatus: error.httpStatus ?? 401 };
  }
  return { source: 'transport', httpStatus: error?.httpStatus };
}

async function handleStreamError(
  error: any,
  captureLabel: string,
  conversationID: number,
  stableId: string,
  dispatch: AppDispatch,
): Promise<boolean> {
  if (!error || typeof error !== 'object') {
    const msg = String(error);
    void captureError(captureLabel, new Error(msg), { conversationID: String(conversationID) });
    dispatch(setError({ conversationID, error: msg, retryability: classifyErrorRetryability(msg) }));
    dispatch(clearStreamingContent({ conversationID }));
    abortControllers.delete(stableId);
    reportClientErrorToServer(conversationID, msg);
    return false;
  }
  if (error.name === 'AbortError') return true;
  const { source, httpStatus } = classifyError(error);
  // v3: the durable rows are the source of truth and reconnect is handled in conversation-stream-client;
  // by the time an error reaches here the turn genuinely failed, so surface it. Classify whether a
  // "Try again" can plausibly succeed (transient) or would deterministically re-fail (terminal, e.g.
  // context-length → steer to a new conversation instead of a retry that loops). A session-expiry
  // (401) is always terminal — a retry with the same dead session re-fails.
  const errMsg = error.message || 'Unknown error';
  const retryability = source === 'session' ? 'terminal' : classifyErrorRetryability(errMsg);
  void captureError(captureLabel, error, { conversationID: String(conversationID) });
  dispatch(setError({ conversationID, error: errMsg, retryability }));
  dispatch(clearStreamingContent({ conversationID }));
  abortControllers.delete(stableId);
  reportClientErrorToServer(conversationID, error.message || 'Unknown error', source, httpStatus);
  return false;
}

// ---------------------------------------------------------------------------
// v3 chat path (dedicated conversations/messages tables + LISTEN/NOTIFY streaming)
// ---------------------------------------------------------------------------

/** Map stream-derived pending tool calls to the ToolCall shape the pending machinery expects. */
function v3PendingToToolCalls(pending: { id: string; name: string; arguments: Record<string, unknown> }[]) {
  return pending.map((p) => ({ id: p.id, type: 'function' as const, function: { name: p.name, arguments: p.arguments } }));
}

/**
 * Run one v3 turn (new message or resume) from the listener: stream live deltas, then reload the
 * durable log and finalize. On a frontend-tool pause, set pending_tool_calls (triggering the
 * auto-exec machinery → completeToolCall → v3 resume). Throws on error so handleStreamError shows it.
 */
async function runV3TurnInListener(
  conversationID: number,
  conversation: ReturnType<typeof selectConversation>,
  turn: V3TurnInput,
  dispatch: AppDispatch,
  signal: AbortSignal,
): Promise<void> {
  if (!conversation) return;

  let status: 'idle' | 'paused' | 'error' = 'idle';
  let runError: string | undefined;
  if (IS_TEST) {
    // jsdom has no usable XHR/SSE for the stream — POST the turn, then poll until it settles.
    const res = await fetch(patchApiUrl(`${API_BASE_URL}/api/conversations/${conversationID}/turns`), {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ...(turn.manualRetry ? { manualRetry: true } : {}),
        ...(turn.autoRetry ? { autoRetry: true } : {}),
        ...(turn.userMessage != null ? { userMessage: turn.userMessage } : {}),
        ...(turn.completedToolCalls ? { completedToolCalls: turn.completedToolCalls } : {}),
        ...(turn.agent ? { agent: turn.agent } : {}),
        agentArgs: turn.agentArgs ?? {},
      }),
    });
    if (!res.ok) {
      if (res.status === 401) {
        const err = new Error('Session expired — please sign in again') as Error & { name: string; httpStatus: number };
        err.name = 'SessionExpiredError';
        err.httpStatus = 401;
        throw err;
      }
      throw new Error(`turn failed: HTTP ${res.status}`);
    }
    for (let i = 0; i < 600; i++) {
      const d = await ConversationsAPI.get(conversationID);
      if (d.conversation.runStatus !== 'running') { status = d.conversation.runStatus as typeof status; break; }
      await new Promise((r) => setTimeout(r, 10));
    }
  } else {
    // Track tool-call args from committed assistant messages so a committed tool RESULT can be
    // rendered live (the result entry alone lacks the args the display needs). This makes server
    // tool calls (ExecuteQuery / SearchDBSchema / SearchFiles) appear AS THEY RUN instead of only
    // after the turn settles. The streamed rows are ephemeral — finalize clears + reloads them.
    const toolMeta = new Map<string, ToolCallMeta>();
    const result = await runV3Turn(conversationID, conversation.log_index ?? 0, turn, signal, {
      onDelta: (text) => dispatch(addStreamingMessage({ conversationID, type: 'StreamedContent', payload: { chunk: text } } as never)),
      // Reasoning tokens feed the thinking indicator (streamedThinking), NEVER the reply bubble —
      // rendering them as StreamedContent showed the chain-of-thought as the answer mid-stream.
      onThinkingDelta: (text) => dispatch(addStreamingMessage({ conversationID, type: 'StreamedThinking', payload: { chunk: text } } as never)),
      onPending: () => { /* pending is derived from the reloaded log below */ },
      onMessage: (content) => {
        for (const [id, meta] of collectToolCallMeta(content)) toolMeta.set(id, meta);
        const toolCallId = (content as { toolCallId?: string } | null)?.toolCallId;
        const streamed = piToolResultToStreamedCall(content, toolCallId ? toolMeta.get(toolCallId) : undefined);
        if (streamed) dispatch(addStreamingMessage({ conversationID, type: 'ToolCompleted', payload: streamed } as never));
      },
    });
    // 'remote' (Remote Agent Session holds the conversation) settles this helper like idle — the
    // remote observer path owns rendering/pending in that mode, not the turn runner.
    status = result.status === 'running' || result.status === 'remote' ? 'idle' : result.status;
    runError = result.error;
  }
  // Reload the durable log for the final render (one source of truth). Also carries errors[] — the
  // v3 stream only signals a bare terminal `status:'error'` and never puts the message on the wire,
  // so `runError` is undefined; the real cause was persisted to errors[]. Fetch it BEFORE surfacing
  // the error so the user sees the actual message instead of a generic "chat error".
  const detail = await ConversationsAPI.get(conversationID);
  if (status === 'error') {
    const lastErr = detail.errors[detail.errors.length - 1];
    throw new Error(runError || lastErr?.message || 'chat error');
  }

  const piLog = detail.messages.map((m) => m.content) as unknown as ConversationLog;
  const errors = detail.errors.map((e) => ({
    source: e.source, message: e.message,
    timestamp: Date.parse(e.createdAt) || Date.now(),
    ...(e.details ? { details: e.details } : {}),
    ...(e.parentPiId ? { parent_id: e.parentPiId } : {}),
  }));
  const { messages } = parsePiConversation(piLog, errors as never);

  dispatch(clearStreamingContent({ conversationID }));
  dispatch(loadConversation({
    conversation: {
      ...conversation,
      conversationID,
      messages,
      log_index: piLog.length,
      pending_tool_calls: [],
      streamedCompletedToolCalls: [],
      streamedThinking: '',
      executionState: status === 'paused' ? 'EXECUTING' : 'FINISHED',
      version: 3,
    },
    setAsActive: false,
  }));

  // Paused on frontend tools → set pending (triggers the auto-exec listener → completeToolCall → resume).
  if (status === 'paused') {
    const pending = derivePendingToolCalls(piLog);
    if (pending.length > 0) {
      dispatch(updateConversation({
        conversationID,
        log_index: piLog.length,
        completed_tool_calls: [],
        pending_tool_calls: v3PendingToToolCalls(pending) as never,
        debug: [],
      }));
    }
  }
}


// ---------------------------------------------------------------------------
// Listeners
// ---------------------------------------------------------------------------

/**
 * createConversation → v3 turn (runV3TurnInListener)
 * Used for new conversations with the initial message.
 */
chatListenerMiddleware.startListening({
  actionCreator: createConversation,
  effect: async (action, listenerApi) => {
    const { conversationID, message } = action.payload;
    if (!message) return;

    const state = listenerApi.getState() as RootState;
    const conversation = selectConversation(state, conversationID);
    if (!conversation) return;

    const dispatch = listenerApi.dispatch as AppDispatch;
    const abortController = new AbortController();
    abortControllers.set(conversation._id, abortController);

    emitSyntheticSkillLoads(conversationID, conversation, dispatch);

    try {
      await runV3TurnInListener(conversationID, conversation,
        { userMessage: message, agent: conversation.agent, agentArgs: conversation.agent_args },
        dispatch, abortController.signal);
    } catch (error: any) {
      if (await handleStreamError(error, 'chatListener:createConversation', conversationID, conversation._id, dispatch)) return;
    }
  }
});

/**
 * sendMessage → v3 turn (runV3TurnInListener)
 * Used for adding messages to existing conversations.
 */
chatListenerMiddleware.startListening({
  actionCreator: sendMessage,
  effect: async (action, listenerApi) => {
    const { conversationID, message } = action.payload;
    const state = listenerApi.getState() as RootState;
    const conversation = selectConversation(state, conversationID);
    if (!conversation) return;

    const dispatch = listenerApi.dispatch as AppDispatch;
    const abortController = new AbortController();
    abortControllers.set(conversation._id, abortController);

    emitSyntheticSkillLoads(conversationID, conversation, dispatch);

    try {
      await runV3TurnInListener(conversationID, conversation,
        { userMessage: message, agent: conversation.agent, agentArgs: conversation.agent_args },
        dispatch, abortController.signal);
    } catch (error: any) {
      if (await handleStreamError(error, 'chatListener:sendMessage', conversationID, conversation._id, dispatch)) return;
    }
  }
});

/**
 * retryConversationTurn → v3 MANUAL retry of a transient-failed turn.
 * Replays the dead turn server-side (truncate its partial rows + replay the preserved user message,
 * budget reset so the click is uncapped) — no "Continue" bubble is appended. Used by the "Try again"
 * affordance for transient errors only; terminal errors don't offer it.
 */
chatListenerMiddleware.startListening({
  actionCreator: retryConversationTurn,
  effect: async (action, listenerApi) => {
    const { conversationID } = action.payload;
    const state = listenerApi.getState() as RootState;
    const conversation = selectConversation(state, conversationID);
    if (!conversation) return;

    const dispatch = listenerApi.dispatch as AppDispatch;
    const abortController = new AbortController();
    abortControllers.set(conversation._id, abortController);

    try {
      await runV3TurnInListener(conversationID, conversation,
        { manualRetry: true, agent: conversation.agent, agentArgs: conversation.agent_args },
        dispatch, abortController.signal);
    } catch (error: any) {
      if (await handleStreamError(error, 'chatListener:retryConversationTurn', conversationID, conversation._id, dispatch)) return;
    }
  }
});

/**
 * editAndForkMessage → fork the v3 conversation, then run the edited message on the fork.
 * The editAndForkMessage action already set conversation.log_index = logIndex before this runs.
 */
chatListenerMiddleware.startListening({
  actionCreator: editAndForkMessage,
  effect: async (action, listenerApi) => {
    const { conversationID, message } = action.payload;
    const state = listenerApi.getState() as RootState;
    const conversation = selectConversation(state, conversationID);
    if (!conversation) return;

    const dispatch = listenerApi.dispatch as AppDispatch;
    const abortController = new AbortController();
    abortControllers.set(conversation._id, abortController);

    emitSyntheticSkillLoads(conversationID, conversation, dispatch);

    try {
      // Fork the conversation at the edit point (copies messages [0, log_index)), then run the
      // edited message on the new conversation. updateConversation moves Redux to the fork
      // (carrying the reducer-truncated messages) + flags the source forked → triggers nav.
      const forkRes = await fetch(patchApiUrl(`${API_BASE_URL}/api/conversations/${conversationID}/fork`), {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ atSeq: conversation.log_index }),
      });
      if (!forkRes.ok) throw new Error(`fork failed: HTTP ${forkRes.status}`);
      // The fork route replies with a successResponse envelope: `{ success, data: { id, ... } }`.
      // Unwrap `data` before reading `id` (mirrors ConversationsAPI's `unwrap`) — reading the
      // top-level `id` yields undefined, which silently skips the fork + never starts the agent.
      const forkBody = await forkRes.json() as { id?: number; data?: { id?: number } };
      const newId = forkBody.data?.id ?? forkBody.id;
      if (!newId) throw new Error('fork failed: missing conversation id in response');
      dispatch(updateConversation({ conversationID, newConversationID: newId, log_index: conversation.log_index, completed_tool_calls: [], pending_tool_calls: [], debug: [] }));
      const forked = selectConversation(listenerApi.getState() as RootState, newId);
      await runV3TurnInListener(newId, forked,
        { userMessage: message, agent: conversation.agent, agentArgs: conversation.agent_args },
        dispatch, abortController.signal);
    } catch (error: any) {
      if (await handleStreamError(error, 'chatListener:editAndFork', conversationID, conversation._id, dispatch)) return;
    }
  }
});

/**
 * completeToolCall → v3 resume (runV3TurnInListener)
 * Fires when all pending frontend tools are done; resumes the conversation.
 */
chatListenerMiddleware.startListening({
  actionCreator: completeToolCall,
  effect: async (action, listenerApi) => {
    const { conversationID } = action.payload;
    const state = listenerApi.getState() as RootState;
    const conversation = selectConversation(state, conversationID);
    if (!conversation) return;
    if (conversation.executionState !== 'EXECUTING') return;

    const allCompleted = selectAllToolsCompleted(state, conversationID);
    if (!allCompleted) return;

    const dispatch = listenerApi.dispatch as AppDispatch;
    let abortController = abortControllers.get(conversation._id);
    if (!abortController) {
      abortController = new AbortController();
      abortControllers.set(conversation._id, abortController);
    }

    try {
      const completed_tool_calls = conversation.pending_tool_calls.map(p => [p.toolCall, p.result!]);

      const queueStrategy = selectQueueStrategy(listenerApi.getState() as RootState);
      const queuedMessages = conversation.queuedMessages;
      const shouldFlushMidTurn = selectAllowChatQueue(listenerApi.getState() as RootState) && queueStrategy === 'mid-turn' && queuedMessages && queuedMessages.length > 0;
      const userMessage = shouldFlushMidTurn ? queuedMessages.map(qm => qm.message).join('\n\n') : null;
      if (shouldFlushMidTurn) {
        dispatch(flushQueuedMessages({ conversationID }));
      }

      // Resume the v3 turn with the executed frontend-tool results (+ any mid-turn queued message).
      await runV3TurnInListener(conversationID, conversation,
        { completedToolCalls: completed_tool_calls, ...(userMessage ? { userMessage } : {}), agent: conversation.agent, agentArgs: conversation.agent_args },
        dispatch, abortController.signal);
    } catch (error: any) {
      if (await handleStreamError(error, 'chatListener:completeToolCall', conversationID, conversation._id, dispatch)) return;
    }
  }
});

/**
 * updateConversation | setUserInputResult → Execute pending frontend tools automatically.
 */
// Tool calls currently executing — guards against concurrent listener firings
// re-running a call whose async result isn't set yet (a re-execution storm).
// eslint-disable-next-line no-restricted-syntax -- client-side Redux listener; per-tab ephemeral execution state, no data leakage
const inFlightToolCalls = new Set<string>();

/** Hard ceiling on one frontend tool execution (see withToolWatchdog) — 6 minutes. */
const TOOL_WATCHDOG_MS = 6 * 60 * 1000;

chatListenerMiddleware.startListening({
  matcher: isAnyOf(updateConversation, setUserInputResult),
  effect: async (action: any, listenerApi) => {
    const conversationID = action.payload.conversationID;
    const state = listenerApi.getState() as RootState;
    const conversation = selectConversation(state, conversationID);

    if (!conversation) return;

    const realConversationID = conversation.forkedConversationID || conversationID;

    const realConversation = realConversationID !== conversationID
      ? selectConversation(state, realConversationID)
      : conversation;

    if (!realConversation) return;

    const runOne = async (pendingTool: (typeof realConversation.pending_tool_calls)[number]) => {
      try {
        console.log(`[chatListener] Executing tool: ${pendingTool.toolCall.function?.name}`);

        // Dynamic import to avoid circular dependencies:
        // tool-handlers → store → chatListener → tool-handlers (circular)
        // eslint-disable-next-line no-restricted-syntax
        const { executeToolCall } = await import('@/lib/tools/tool-handlers');

        const state = listenerApi.getState() as RootState;

        // Reuse (or register) the conversation's abort controller — same map interruptChat/Stop
        // aborts — so a long-running tool query (e.g. a story embed) can be cancelled immediately
        // instead of running to its timeout. Mirrors the completeToolCall resume listener.
        let toolAbort = abortControllers.get(realConversation._id);
        if (!toolAbort) {
          toolAbort = new AbortController();
          abortControllers.set(realConversation._id, toolAbort);
        }

        // Watchdog: a handler that never settles (hung fetch with no timeout, stuck upload) would
        // otherwise never dispatch completeToolCall and leave the conversation in "executing"
        // forever. The deadline sits well above the worst LEGITIMATE tool run (two 120s query
        // waves + uploads ≈ 4min); a UserInputException still propagates immediately.
        const result = await withToolWatchdog(
          executeToolCall(
            pendingTool.toolCall,
            listenerApi.dispatch as AppDispatch,
            toolAbort.signal,
            state,
            pendingTool.userInputs
          ),
          pendingTool.toolCall.function?.name ?? 'tool',
          TOOL_WATCHDOG_MS,
        );

        listenerApi.dispatch(completeToolCall({
          conversationID: realConversationID,
          tool_call_id: pendingTool.toolCall.id,
          result: {
            ...result,
            created_at: new Date().toISOString()
          } as any
        }));

      } catch (error: any) {
        if (error instanceof UserInputException) {
          console.log(`[chatListener] Tool requests user input:`, error.props);
          listenerApi.dispatch(addUserInputRequest({
            conversationID: realConversationID,
            tool_call_id: pendingTool.toolCall.id,
            userInput: {
              id: generateUniqueId(),
              props: error.props,
              result: undefined,
              providedAt: undefined
            }
          }));
        } else {
          console.error(`[chatListener] Tool execution failed:`, error);
          listenerApi.dispatch(completeToolCall({
            conversationID: realConversationID,
            tool_call_id: pendingTool.toolCall.id,
            result: {
              role: 'tool',
              tool_call_id: pendingTool.toolCall.id,
              content: JSON.stringify({
                success: false,
                error: error instanceof Error ? error.message : String(error)
              }),
              created_at: new Date().toISOString()
            }
          }));
        }
      } finally {
        inFlightToolCalls.delete(pendingTool.toolCall.id);
      }
    };

    const eligible = realConversation.pending_tool_calls.filter(t =>
      !t.result &&
      !t.userInputs?.some(ui => ui.result === undefined) &&
      !inFlightToolCalls.has(t.toolCall.id)
    );
    // Mark in-flight synchronously (before the awaits) so a concurrent firing skips these.
    for (const t of eligible) inFlightToolCalls.add(t.toolCall.id);

    // Group by fileId: same fileId → serial; different fileId → parallel
    const groups = new Map<string, typeof eligible>();
    for (const tool of eligible) {
      const toolArgs = tool.toolCall.function?.arguments || {};
      const key = toolArgs.fileId != null ? String(toolArgs.fileId) : `_${tool.toolCall.id}`;
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key)!.push(tool);
    }

    await Promise.all(
      Array.from(groups.values()).map(async (group) => {
        for (const tool of group) {
          await runOne(tool);
        }
      })
    );
  }
});

/**
 * interruptChat → Abort the active conversation stream.
 */
chatListenerMiddleware.startListening({
  actionCreator: interruptChat,
  effect: async (action, listenerApi) => {
    const { conversationID } = action.payload;
    const state = listenerApi.getState() as RootState;
    const conversation = selectConversation(state, conversationID);

    if (!conversation) {
      console.warn(`[interruptChat] Conversation ${conversationID} not found`);
      return;
    }

    const abortController = abortControllers.get(conversation._id);
    if (abortController) {
      console.log(`[interruptChat] Aborting conversation ${conversationID} (_id: ${conversation._id})`);
      abortController.abort();
    } else {
      console.warn(`[interruptChat] No AbortController found for conversation ${conversationID}`);
    }

    // Also cancel the run server-side. Turns are decoupled from connections (so transport drops can
    // resume) — aborting the local stream alone would leave the engine running (billing tokens) to
    // completion. v3 conversations interrupt via their own endpoint (NOTIFY → orchestrator.cancel).
    // Best-effort.
    if (conversationID > 0) {
      try {
        await fetch(patchApiUrl(`${API_BASE_URL}/api/conversations/${conversationID}/interrupt`), {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
        });
      } catch (err) {
        console.warn('[interruptChat] server-side interrupt failed (best-effort):', err);
      }
    }
  }
});

/**
 * updateConversation | queueMessage → Auto-send queued messages when conversation finishes.
 */
chatListenerMiddleware.startListening({
  matcher: isAnyOf(updateConversation, queueMessage),
  effect: async (action: any, listenerApi) => {
    const state = listenerApi.getState() as RootState;
    if (!selectAllowChatQueue(state)) return;
    const effectiveId = action.payload.newConversationID || action.payload.conversationID;
    const conversation = selectConversation(state, effectiveId);

    if (!conversation || conversation.executionState !== 'FINISHED') return;
    if (!conversation.queuedMessages || conversation.queuedMessages.length === 0) return;
    if (conversation.wasInterrupted) return;

    const combinedMessage = conversation.queuedMessages.map(qm => qm.message).join('\n\n');
    const allAttachments = conversation.queuedMessages.flatMap(qm => qm.attachments || []);

    listenerApi.dispatch(clearQueuedMessages({ conversationID: effectiveId }));
    listenerApi.dispatch(sendMessage({
      conversationID: effectiveId,
      message: combinedMessage,
      attachments: allAttachments.length > 0 ? allAttachments : undefined,
    }));
  }
});
