/**
 * Generates `lib/dashboard-surface/chrome-css.gen.ts` — the ONE static stylesheet the
 * self-contained dashboard iframe surface needs (Renderer_v2 Phase 8a).
 *
 * Dashboards have no authored classes: every class inside the surface comes from our own
 * components — the kit, the re-skinned embed chrome (shared with stories), and the
 * dashboard-view chrome listed below — a closed set. So unlike stories (compiled per story at
 * save/read time), the dashboard sheet is compiled ONCE, at build time, and shipped as a string
 * module. react-grid-layout's library CSS is prepended (the compiled chrome wins ties on
 * document order).
 *
 * Run: npm run generate-dashboard-chrome-css
 * A freshness test (lib/dashboard-surface/__tests__/chrome-css.test.ts) fails when this file
 * is stale relative to the chrome sources.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { extractRecipeClasses, EMBED_CHROME_FILES } from './generate-story-ui-classes';
import { storyThemeCss } from '../lib/data/story/story-themes';
// server-only module: running this script requires `--conditions react-server` (the npm script
// sets it — same contract as generate-app-theme-css).
import { compileChromeCss } from '../lib/data/story/story-css.server';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_FILE = join(ROOT, 'lib', 'dashboard-surface', 'chrome-css.gen.ts');

/**
 * Dashboard-view chrome that renders INSIDE the surface but is not part of the story embed
 * chrome: the grid view itself, windowing ghosts, text blocks, the edit-mode browser panel,
 * empty states, and the param widgets' remaining leaves. Add each new dashboard-surface
 * component here (the freshness test fails if the artifact goes stale, not if this list is
 * incomplete — review this list when adding components to the dashboard tree).
 */
export const DASHBOARD_CHROME_FILES = [
  // The surface host itself: it stamps base classes (text-foreground) on the surface root.
  join(ROOT, 'components', 'views', 'shared', 'DashboardSurface.tsx'),
  join(ROOT, 'components', 'views', 'DashboardView.tsx'),
  join(ROOT, 'components', 'views', 'dashboard', 'WindowedTile.tsx'),
  join(ROOT, 'components', 'TextBlockCard.tsx'),
  join(ROOT, 'components', 'question', 'QuestionBrowserPanel.tsx'),
  join(ROOT, 'components', 'views', 'shared', 'empty-states.tsx'),
  join(ROOT, 'components', 'containers', 'EmbeddedQuestionContainer.tsx'),
  join(ROOT, 'components', 'params', 'SourceConfigPopover.tsx'),
  join(ROOT, 'components', 'params', 'paramInputShared.ts'),
  join(ROOT, 'components', 'selectors', 'DatePicker.tsx'),
];

/** Every Tailwind candidate the dashboard surface can need: kit ∪ story embed chrome ∪ dashboard chrome. */
export function collectDashboardChromeCandidates(): string[] {
  return extractRecipeClasses(join(ROOT, 'components', 'kit'), [
    ...EMBED_CHROME_FILES,
    ...DASHBOARD_CHROME_FILES,
  ]);
}

/**
 * Static library stylesheets the surface needs: react-grid-layout (item positioning,
 * placeholder, resize handles) and react-day-picker (the DatePicker calendar portals into the
 * iframe body — its app-global css import never reaches the iframe).
 */
export function readGridLibraryCss(): string {
  const require = createRequire(import.meta.url);
  return [
    readFileSync(require.resolve('react-grid-layout/css/styles.css'), 'utf8'),
    readFileSync(require.resolve('react-day-picker/dist/style.css'), 'utf8'),
  ].join('\n');
}

/**
 * Compile-environment version stamped into the artifact: candidates + library css + the theme
 * token emitter output (theme blocks ship inside the compiled sheet). djb2 — stability matters,
 * cryptographic strength doesn't (same contract as storyCssCompileVersion).
 */
export function dashboardChromeVersion(candidates: string[], libCss: string): string {
  const src = `${candidates.join(' ')}|${libCss}|${storyThemeCss()}`;
  let h = 5381;
  for (let i = 0; i < src.length; i++) h = ((h << 5) + h + src.charCodeAt(i)) | 0;
  return `v${(h >>> 0).toString(36)}`;
}

async function main() {
  const candidates = collectDashboardChromeCandidates();
  const libCss = readGridLibraryCss();
  const compiled = await compileChromeCss(candidates);
  const css = `${libCss}\n${compiled}`;
  const version = dashboardChromeVersion(candidates, libCss);
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(
    OUT_FILE,
    `/**
 * GENERATED by scripts/generate-dashboard-chrome-css.ts — do not edit by hand.
 * The self-contained dashboard surface's ONLY stylesheet (Renderer_v2 Phase 8a):
 * react-grid-layout library css + the compiled chrome utilities (kit + embed chrome +
 * dashboard view chrome) + shadcn token layer + design-theme blocks.
 * Regenerate with: npm run generate-dashboard-chrome-css
 */
export const DASHBOARD_CHROME_CSS_VERSION = ${JSON.stringify(version)};
export const DASHBOARD_CHROME_CSS: string = ${JSON.stringify(css)};
`,
  );
  console.log(`wrote ${css.length} bytes (${candidates.length} candidates, ${version}) to lib/dashboard-surface/chrome-css.gen.ts`);
}

// Run only when executed directly — the freshness test imports the helpers and must not rewrite.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
