/**
 * Regenerate lib/story-ui/recipe-classes.ts — the Tailwind candidate tokens used by the
 * vendored shadcn component sources (Story_Design_V2 §3). The per-story compile extracts
 * candidates from STORY markup only; component chrome classes (rounded-xl, shadow-sm, …)
 * live in the component sources, so they are pre-extracted here and unioned at compile
 * time for format:'jsx' stories.
 *
 * Run after changing anything under lib/story-ui/components/:
 *   npm run generate-story-ui-classes
 * A freshness test (lib/story-ui/__tests__/recipe-classes.test.ts) fails when this file
 * is stale. Extraction is a deliberate superset: every whitespace-separated token of every
 * string literal in the sources. Non-class tokens are harmless — Tailwind emits nothing
 * for candidates it doesn't recognize.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const COMPONENTS_DIR = join(ROOT, 'lib', 'story-ui', 'components');
const OUT_FILE = join(ROOT, 'lib', 'story-ui', 'recipe-classes.ts');

export function extractRecipeClasses(dir: string): string[] {
  const tokens = new Set<string>();
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.tsx')).sort()) {
    const src = readFileSync(join(dir, file), 'utf8');
    // Every string literal (' " `) — cva recipes, className constants, template chunks.
    for (const m of src.matchAll(/'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)"|`((?:[^`\\]|\\.)*)`/g)) {
      const lit = m[1] ?? m[2] ?? m[3] ?? '';
      for (const tok of lit.split(/\s+/)) {
        // Plausible utility tokens only: no quotes/braces/template holes, at least one letter.
        if (tok && !/[{}$'"`<>]/.test(tok) && /[a-zA-Z]/.test(tok)) tokens.add(tok);
      }
    }
  }
  return [...tokens].sort();
}

function main() {
  const classes = extractRecipeClasses(COMPONENTS_DIR);
  const body = classes.map((c) => `  ${JSON.stringify(c)},`).join('\n');
  writeFileSync(
    OUT_FILE,
    `/**
 * GENERATED by scripts/generate-story-ui-classes.ts — do not edit by hand.
 * Tailwind candidate tokens extracted from lib/story-ui/components sources; unioned with
 * per-story candidates when compiling format:'jsx' story CSS (see story-css.server.ts).
 * Regenerate with: npm run generate-story-ui-classes
 */
export const STORY_UI_RECIPE_CLASSES: readonly string[] = [
${body}
];
`,
  );
  console.log(`wrote ${classes.length} tokens to lib/story-ui/recipe-classes.ts`);
}

// Run only when executed directly (npm run generate-story-ui-classes) — the freshness test
// imports extractRecipeClasses and must not trigger a rewrite.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
