export const thinkingPhrases = [
  'Thinking',
  'Pondering life choices',
  'Analyzing',
  'Consulting the oracle',
  'Crunching numbers',
  'Spinning up neurons',
  'Computing',
  'Doing math stuff',
  'Evaluating',
  'Overthinking',
  'Calculating',
  'Counting to infinity',
  'Reasoning',
  'Existential crisis-ing',
  'Searching',
  'Looking under the rug',
  'Querying',
  'Summoning data spirits',
  'Working',
  'Churning data',
];
