export const thinkingPhrases = [
  'Thinking',
  'Pondering life choices',
  'Analyzing',
  'Consulting the oracle',
  'Processing',
  'Spinning up neurons',
  'Computing',
  'Doing math stuff',
  'Evaluating',
  'Overthinking',
  'Calculating',
  'Counting to infinity',
  'Reasoning',
  'Having an existential crisis',
  'Searching',
  'Looking under the rug',
  'Querying',
  'Summoning data spirits',
  'Working',
  'Churning data',
  'Crunching numbers',
];
