/**
 * ReadFiles - Load multiple files with references and query results
 *
 * Phase 1: Enhanced with auto-fetching, TTL-based caching, and promise deduplication
 *
 * Features:
 * - Fetches missing files automatically (no more "File not found" errors)
 * - TTL-based cache freshness checks
 * - Promise deduplication for concurrent requests
 * - Skip option to bypass fetching
 * - Extensible augmentation registry for type-specific processing
 *
 * Improvements over read-files.client.ts:
 * - Actually fetches files if missing/stale (instead of throwing error)
 * - Promise deduplication prevents redundant API calls
 * - Flexible TTL control per request
 * - Direct store import (no getState parameter)
 * - Registry pattern for type-specific augmentation
 *
 * Also owns readFolder — it shares the "load metadata into Redux with TTL
 * caching + permission filtering" concern with the file-read functions above.
 */

import { getStore } from '@/store/store';
import { selectFile, selectIsFileLoaded, selectIsFileFresh, setFile, setFiles, setLoading, setFolderLoading, setLoadError, selectFileIdByPath, selectIsFolderFresh, setFileInfo, setFolderInfo, selectFiles, setFilePlaceholder, type FileState } from '@/store/filesSlice';
import { selectEffectiveUser } from '@/store/authSlice';
import { FilesAPI, getFiles } from '@/lib/data/files';
import { CACHE_TTL } from '@/lib/constants/cache';
import { isHiddenSystemPath } from '@/lib/mode/path-resolver';
import { canViewFileType } from '@/lib/auth/access-rules.client';
import { getRootParams } from '@/lib/data/helpers/param-resolution';
import type { AugmentedFile, QuestionContent } from '@/lib/types';
import type { LoadError } from '@/lib/types/errors';
import { createLoadErrorFromException } from '@/lib/types/errors';
import { selectAugmentedFiles } from '@/lib/store/file-selectors';
import { getQueryResult } from '@/lib/file-state/query-results';
import { cacheSpreadsheetSource } from '@/lib/spreadsheet/result-cache';
import { getQuestionExecution } from '@/lib/spreadsheet/question-source';
import { hashString, PromiseManager } from '@/lib/file-state/shared';
import type {
  ReadFilesOptions,
  ReadFilesByCriteriaOptions,
  ReadFolderOptions,
  ReadFolderResult,
} from '@/lib/file-state/file-state-interface';

function pathToPlaceholderId(path: string): number {
  // Negative (virtual, no DB row) and kept within int4 range [-2^31, -1] so it
  // never overflows an `integer` column if it reaches one. Must match
  // store/filesSlice.ts:pathToVirtualId so the same path yields the same ID.
  return -(1 + (Math.abs(hashString(path)) % 2_000_000_000));
}

/**
 * Global promise manager for in-flight file fetches
 * Export for testing and debugging (e.g., filePromises.clear(), filePromises.size)
 */
export const filePromises = new PromiseManager<void>();

/**
 * LoadFiles - Fetch missing/stale files into Redux (Steps 1+2 of readFiles)
 *
 * Never re-throws — all errors end up in file.loadError in Redux.
 *
 * @param fileIds - File IDs to check and potentially fetch
 * @param ttl - Time-to-live in ms for cache freshness
 * @param skip - If true, skip fetching entirely
 */
export async function loadFiles(fileIds: number[], ttl: number, skip: boolean): Promise<void> {
  const state = getStore().getState();

  // Determine which files need fetching.
  // Negative IDs are virtual/placeholder IDs generated by pathToVirtualId() —
  // they have no DB row and must never be sent to the batch API.
  const needsFetch = fileIds.filter(id => {
    if (id == null || !Number.isFinite(id) || id < 0) return false;
    if (skip) return false;
    return !selectIsFileLoaded(state, id) || !selectIsFileFresh(state, id, ttl);
  });

  if (needsFetch.length === 0) return;

  // Sort IDs for consistent cache key
  const key = [...needsFetch].sort((a, b) => a - b).join(',');

  // Set loading state for files being fetched
  needsFetch.forEach(id => getStore().dispatch(setLoading({ id, loading: true })));

  try {
    await filePromises.execute(key, async () => {
      const result = await FilesAPI.loadFiles(needsFetch);
      getStore().dispatch(setFiles({
        files: result.data,
        references: result.metadata.references || [],
        analyticsMap: result.metadata.analytics || {},
      }));
      // setFiles sets loading: false on all stored files
    });
  } catch (error) {
    // Store error in Redux — do NOT re-throw
    getStore().dispatch(setLoadError({ ids: needsFetch, error: createLoadErrorFromException(error) }));
    return;
  }

  // Post-fetch: mark files not returned by the API as NOT_FOUND
  const afterState = getStore().getState();
  const notFound = needsFetch.filter(id => {
    const file = selectFile(afterState, id);
    return !file || file.updatedAt === 0;
  });
  if (notFound.length > 0) {
    getStore().dispatch(setLoadError({
      ids: notFound,
      error: { message: 'File not found', code: 'NOT_FOUND' }
    }));
  }
}

/**
 * SelectAugmentedFiles - Pure selector: read files + references + query results from Redux
 *
 * No async, no side-effects. Can be used in hooks via useSelector.
 *
 * @param state - Redux state
 * @param fileIds - File IDs to select
 * @returns ReadFilesOutput
 */
/**
 * loadFileByPath - Fetch a file by path into Redux
 *
 * Never re-throws — callers handle errors in local state.
 *
 * @param path - File path to load
 * @param ttl - Time-to-live in ms for cache freshness
 */
export async function loadFileByPath(path: string, ttl: number = CACHE_TTL.FILE): Promise<void> {
  const state = getStore().getState();
  const existingId = selectFileIdByPath(state, path);
  // Skip if a real (positive-ID) file is already fresh
  if (existingId && existingId > 0
      && selectIsFileLoaded(state, existingId)
      && selectIsFileFresh(state, existingId, ttl)) {
    return;
  }
  // Synchronously create loading placeholder in Redux (pathIndex updated too)
  getStore().dispatch(setFilePlaceholder(path));
  try {
    const response = await FilesAPI.loadFileByPath(path);
    // setFile reducer auto-deletes the placeholder and updates pathIndex
    getStore().dispatch(setFile({ file: response.data, references: [] }));
  } catch (err) {
    getStore().dispatch(setLoadError({
      ids: [pathToPlaceholderId(path)],
      error: createLoadErrorFromException(err)
    }));
  }
}

/**
 * ReadFiles - Load multiple files with references and query results
 *
 * @param input - File IDs to load
 * @param options - { ttl?: number, skip?: boolean, runQueries?: boolean }
 * @returns Augmented files with references and query results
 */
export async function readFiles(
  fileIds: number[],
  options: ReadFilesOptions = {}
): Promise<AugmentedFile[]> {
  const { ttl = CACHE_TTL.FILE, skip = false, runQueries = false, signal } = options;

  await loadFiles(fileIds, ttl, skip);

  if (runQueries) {
    const state = getStore().getState();
    const preAugmented = selectAugmentedFiles(state, fileIds);
    // Execute under the CANONICAL params the augmentation selector looks up with
    // (buildQueryParamValues = effective + None-coerced) so the stored cache key === the lookup key
    // === the file's queryResultId. References from selectAugmentedFiles are already
    // buildEffectiveReference'd (inherited params baked into their content), so they pass inherited
    // {}; the root inherits from itself (a dashboard/story passes its params to its questions).
    const runs: Promise<unknown>[] = [];
    for (const a of preAugmented) {
      const rootInherited = getRootParams(state, a.fileState);
      const entries: Array<{ f: FileState; inherited: Record<string, unknown> }> = [
        { f: a.fileState, inherited: rootInherited },
        ...a.references.map(f => ({ f, inherited: {} as Record<string, unknown> })),
      ];
      for (const { f, inherited } of entries) {
        if (f.type !== 'question') continue;
        const content = f.content as QuestionContent | undefined;
        const execution = getQuestionExecution(content, inherited);
        if (!execution) continue;
        if (execution.kind === 'spreadsheet') {
          cacheSpreadsheetSource(execution.spreadsheet);
          continue;
        }
        runs.push(getQueryResult({
          query: execution.query,
          params: execution.params,
          database: execution.database,
          filePath: f.path,
          fileId: f.id,
          fileVersion: f.version,
        }, signal ? { signal } : undefined));
      }
    }
    await Promise.allSettled(runs);
  }

  return selectAugmentedFiles(getStore().getState(), fileIds);
}


/**
 * In-flight request deduplication for readFilesByCriteria. Multiple components
 * in the same page tree (e.g. file detail at /f/:id) commonly request files
 * by overlapping criteria (5× connection/depth=1, 2× context/depth=-1, ...)
 * in the same React commit. Without dedupe each call fires its own HTTP
 * request — Sentry flagged this as MINUSX-BI-7 (N+1 API Call) and
 * MINUSX-BI-B (HTTP/1.1 Overhead, 15× GET /api/files). Sharing a single
 * in-flight Promise per (criteria, partial) collapses 8 requests to 3 in
 * the trace's repro.
 */
const criteriaInflight = new PromiseManager<AugmentedFile[]>();

/**
 * ReadFilesByCriteria - Load files by criteria (path, type, depth)
 *
 * @param options - Criteria and options
 * @returns Augmented files matching criteria
 */
export async function readFilesByCriteria(
  options: ReadFilesByCriteriaOptions
): Promise<AugmentedFile[]> {
  const { criteria, ttl = CACHE_TTL.FILE, skip = false, partial = false } = options;

  // Dedupe key intentionally excludes `ttl`/`skip` — those only control how
  // we read from the cache (downstream behavior), not which files come back
  // from the network. Two concurrent callers with the same criteria + partial
  // should share a single round-trip.
  const dedupeKey = JSON.stringify({ criteria, partial });

  return criteriaInflight.execute(dedupeKey, async () => {
    // Step 1: Get file metadata matching criteria
    const result = await FilesAPI.getFiles(criteria);
    const fileIds = result.data.map(f => f.id);

    // Step 2: If partial load, store metadata in Redux and return without augmentation
    if (partial) {
      // Store file metadata in Redux so reactive selectors (useFilesByCriteria) can find them
      if (result.data.length > 0) {
        getStore().dispatch(setFileInfo(result.data));
      }
      const state = getStore().getState();
      return fileIds
        .map(id => selectFile(state, id))
        .filter((f): f is FileState => Boolean(f))
        .map(fileState => ({ fileState, references: [], queryResults: [] }));
    }

    // Step 3: Full load with augmentation
    return readFiles(fileIds, { ttl, skip });
  });
}

// ============================================================================
// Read Folder
// ============================================================================

/**
 * readFolder - Load folder contents with TTL caching and permission filtering
 *
 * Behavior:
 * 1. Check if folder is fresh (within TTL) - return cached if fresh
 * 2. If stale/missing, fetch from API (getFiles with path and depth)
 * 3. Store folder file + children in Redux
 * 4. Filter files based on user permissions and hidden system paths
 * 5. Return { files, loading, error }
 *
 * @param path - Folder path (e.g., '/org', '/team')
 * @param options - Options (depth, ttl, forceLoad)
 * @returns Promise<ReadFolderResult>
 *
 * Example:
 * ```typescript
 * const result = await readFolder('/org', { depth: 1 });
 * console.log(result.files); // All accessible files in /org
 * ```
 */
export async function readFolder(
  path: string,
  options: ReadFolderOptions = {}
): Promise<ReadFolderResult> {
  const { depth = 1, ttl = CACHE_TTL.FOLDER, forceLoad = false } = options;

  const state = getStore().getState();


  // Look up folder ID by path
  let folderId = selectFileIdByPath(state, path);

  // Check if folder is fresh
  const isFresh = selectIsFolderFresh(state, path, ttl);

  // Fetch from API if not fresh or forcing reload
  if (!isFresh || forceLoad) {
    // Set loading state (creates placeholder if folder not yet in Redux)
    getStore().dispatch(setFolderLoading({ path, loading: true }));

    try {
      // Fetch folder contents from API
      const response = await getFiles({ paths: [path], depth });

      // Store folder file itself (for pathIndex)
      if (response.metadata.folders.length > 0) {
        getStore().dispatch(setFileInfo(response.metadata.folders));
      }

      // Store children and update folder.references
      getStore().dispatch(setFolderInfo({ path, fileInfos: response.data }));

      // Update folderId after storing
      const updatedState = getStore().getState();
      folderId = selectFileIdByPath(updatedState, path);
    } catch (error) {
      console.error('[readFolder] Failed to load folder:', path, error);

      const loadError: LoadError = {
        message: error instanceof Error ? error.message : String(error),
        code: 'SERVER_ERROR'
      };

      const updatedFolderId = selectFileIdByPath(getStore().getState(), path);
      if (updatedFolderId) {
        getStore().dispatch(setLoadError({ ids: [updatedFolderId], error: loadError }));
      }

      return { files: [], loading: false, error: loadError };
    }
  }

  // Common return path: get from cache (now fresh), strip metadata, filter
  const currentState = getStore().getState();
  const folder = folderId ? selectFile(currentState, folderId) : undefined;
  const childIds = folder?.references || [];
  const allFiles = selectFiles(currentState, childIds);

  // Strip content and edit state to avoid bloating app state
  const metadataOnly = stripFileContent(allFiles);

  // Filter by permissions
  const filteredFiles = await filterFilesByPermissions(metadataOnly);

  return {
    files: filteredFiles,
    loading: false,
    error: null
  };
}

/**
 * Strip content and edit state from files to avoid bloating app state.
 * Used by readFolder() and useAppState() folder path.
 */
function stripFileContent(files: FileState[]): FileState[] {
  return files.map(f => {
    const { content, persistableChanges, ephemeralChanges, metadataChanges, ...rest } = f;
    return rest as FileState;
  });
}

/**
 * Helper: Filter files by user permissions and hidden system paths
 */
async function filterFilesByPermissions(files: FileState[]): Promise<FileState[]> {
  const state = getStore().getState();

  // Get effective user and mode
  const effectiveUser = selectEffectiveUser(state);
  const mode = effectiveUser?.mode || 'org';

  // Import access rules and path helpers

  // Filter by permissions
  return files.filter(file => {
    // Filter by role-based type permissions
    if (!canViewFileType(effectiveUser?.role || 'viewer', file.type)) {
      return false;
    }
    // Filter out hidden system folders
    if (file.type === 'folder' && isHiddenSystemPath(file.path, mode)) {
      return false;
    }
    return true;
  });
}
