// Render-time normalizer: pi-ai ConversationLog → chatSlice ChatMessage[].
//
// Pure function. The slice keeps pi-ai shape; this view function shapes the
// data for the legacy renderer (SimpleChatMessage / AgentTurnContainer /
// ToolCallDisplay) so chat-v2 reuses the polished UI without any chatSlice
// schema changes.
//
// Mapping:
//   AgentInvocation parent_id===null   → UserMessage (root user turn)
//   AgentInvocation parent_id!==null   → CompletedToolCall placeholder (sub-agent dispatched as a tool)
//   AssistantMessage with text         → CompletedToolCall { name:'TalkToUser', content:joined-text, details:{ type:'assistant_text', usage, stopReason, model, ... } }
//   AssistantMessage with toolCall blk → CompletedToolCall placeholder per block
//   AssistantMessage thinking blocks   → folded into the TalkToUser entry as details.thinking
//   ToolResultMessage                  → fills the matching pending CompletedToolCall (content + details + isError-mapped)

import type {
  ConversationLog,
  ConversationLogEntry,
  AgentInvocation,
  StreamEvent,
} from '@/orchestrator/types';
import type {
  AssistantMessage,
  ToolResultMessage,
  ToolCall as PiToolCall,
  TextContent,
  ThinkingContent,
} from '@mariozechner/pi-ai';
import type {
  CompletedToolCall,
  UserMessage,
  DebugMessage,
  AutoGeneratedMessage,
} from '@/store/chatSlice';
import type { Attachment } from '@/lib/types';

export type ChatV2RenderMessage =
  | UserMessage
  | CompletedToolCall
  | DebugMessage
  | AutoGeneratedMessage;

type LogEntry = ConversationLogEntry;
type AgentInvocationEntry = AgentInvocation & { parent_id: string | null };
type AssistantEntry = AssistantMessage & { parent_id: string | null };
type ToolResultEntry = ToolResultMessage & { parent_id: string | null };

function isAgentInvocation(e: LogEntry): e is AgentInvocationEntry {
  return (e as { type?: string }).type === 'toolCall';
}
function isAssistant(e: LogEntry): e is AssistantEntry {
  return 'role' in e && e.role === 'assistant';
}
function isToolResult(e: LogEntry): e is ToolResultEntry {
  return 'role' in e && e.role === 'toolResult';
}

function pickText(content: (TextContent | { type: string })[] | undefined): string {
  if (!content || !Array.isArray(content)) return '';
  return content
    .filter((c): c is TextContent => c.type === 'text')
    .map((c) => c.text)
    .join('\n');
}

function pickThinking(
  content: (ThinkingContent | { type: string })[] | undefined,
): string {
  if (!content || !Array.isArray(content)) return '';
  return content
    .filter((c): c is ThinkingContent => c.type === 'thinking')
    .map((c) => c.thinking)
    .join('\n');
}

function pickToolCalls(content: AssistantMessage['content'] | undefined): PiToolCall[] {
  if (!content || !Array.isArray(content)) return [];
  return content.filter((c): c is PiToolCall => (c as { type?: string }).type === 'toolCall');
}

function tsToIso(ts: number | undefined): string {
  if (typeof ts !== 'number' || !Number.isFinite(ts)) return new Date(0).toISOString();
  return new Date(ts).toISOString();
}

function makePendingToolEntry(opts: {
  toolCallId: string;
  name: string;
  argsObject: Record<string, unknown>;
  createdAt: string;
}): CompletedToolCall {
  return {
    role: 'tool',
    tool_call_id: opts.toolCallId,
    content: '',
    run_id: opts.toolCallId,
    function: { name: opts.name, arguments: JSON.stringify(opts.argsObject ?? {}) },
    created_at: opts.createdAt,
  };
}

function makeAssistantTextEntry(opts: {
  parentAgentId: string;
  text: string;
  thinking: string;
  meta: Pick<
    AssistantMessage,
    'usage' | 'stopReason' | 'model' | 'responseId' | 'diagnostics' | 'errorMessage'
  >;
  createdAt: string;
  index: number;
}): CompletedToolCall {
  const synthId = `assistant_text:${opts.parentAgentId}:${opts.index}`;
  const details: Record<string, unknown> = {
    type: 'assistant_text',
    success: true,
    usage: opts.meta.usage,
    stopReason: opts.meta.stopReason,
    model: opts.meta.model,
  };
  if (opts.meta.responseId) details.responseId = opts.meta.responseId;
  if (opts.meta.diagnostics) details.diagnostics = opts.meta.diagnostics;
  if (opts.meta.errorMessage) details.errorMessage = opts.meta.errorMessage;
  if (opts.thinking) details.thinking = opts.thinking;
  return {
    role: 'tool',
    tool_call_id: synthId,
    content: opts.text,
    run_id: synthId,
    function: { name: 'TalkToUser', arguments: '{}' },
    created_at: opts.createdAt,
    details,
  };
}

/**
 * Project an array of streaming events into synthetic log entries that can be
 * appended to the canonical log before normalization. For each unique
 * parent_id, we keep the LATEST `partial: AssistantMessage` snapshot — pi-ai
 * accumulates content into `partial` on every event, so the latest one is
 * the running state of the in-flight assistant message.
 *
 * Pending tool events become synthetic AgentInvocation entries (sub-agent
 * placeholders), so the renderer shows a "running…" placeholder mid-turn.
 */
function projectStreamingEvents(events: StreamEvent[]): ConversationLogEntry[] {
  const partialByParent = new Map<string, AssistantMessage>();
  const pendingTools: ConversationLogEntry[] = [];
  for (const ev of events) {
    if ((ev as { type?: string }).type === 'pending') {
      const pe = ev as Extract<StreamEvent, { type: 'pending' }>;
      pendingTools.push({
        type: 'toolCall',
        id: pe.id,
        name: pe.name,
        arguments: pe.parameters,
        context: pe.context,
        parent_id: pe.parent_id,
      } as AgentInvocation & { parent_id: string });
      continue;
    }
    const aev = ev as { partial?: AssistantMessage; parent_id?: string };
    if (aev.partial && aev.parent_id) {
      partialByParent.set(aev.parent_id, aev.partial);
    }
  }
  const projected: ConversationLogEntry[] = [];
  for (const [parent_id, partial] of partialByParent) {
    projected.push({ ...partial, parent_id } as AssistantMessage & { parent_id: string });
  }
  return [...projected, ...pendingTools];
}

/**
 * Convert a pi-ai ConversationLog into the chatSlice render shape.
 *
 * Walks the log once, producing UserMessage entries for root invocations and
 * CompletedToolCall entries for assistant text/tool-call blocks. ToolResults
 * fill in their matching pending placeholders.
 *
 * If `streamingEvents` is provided, the latest in-flight `partial`
 * AssistantMessage per parent_id is appended as a synthetic log entry before
 * walking — this makes mid-turn streaming render through the same path as
 * post-turn canonical log.
 */
export function chatV2LogToMessages(
  log: ConversationLog,
  streamingEvents?: StreamEvent[],
): ChatV2RenderMessage[] {
  const projectedLog: ConversationLog =
    streamingEvents && streamingEvents.length > 0
      ? [...log, ...projectStreamingEvents(streamingEvents)]
      : log;
  return chatV2LogToMessagesInternal(projectedLog);
}

function chatV2LogToMessagesInternal(log: ConversationLog): ChatV2RenderMessage[] {
  const out: ChatV2RenderMessage[] = [];
  // tool_call_id → index into `out` for back-fill on ToolResultMessage.
  const pendingByCallId = new Map<string, number>();

  for (let i = 0; i < log.length; i++) {
    const entry = log[i];

    if (isAgentInvocation(entry)) {
      // Root invocation: user message.
      if (entry.parent_id === null) {
        const args = (entry.arguments ?? {}) as {
          userMessage?: unknown;
          attachments?: unknown;
        };
        const content = typeof args.userMessage === 'string' ? args.userMessage : '';
        const attachments = Array.isArray(args.attachments)
          ? (args.attachments as Attachment[])
          : undefined;
        const user: UserMessage = {
          role: 'user',
          content,
          created_at: tsToIso(undefined),
          logIndex: i,
          ...(attachments && attachments.length > 0 ? { attachments } : {}),
        };
        out.push(user);
        continue;
      }

      // Sub-agent invocation: pending tool placeholder. The parent assistant
      // message may already have emitted a placeholder for the same id (it
      // carries this invocation as a toolCall block); if so, this is a no-op.
      if (pendingByCallId.has(entry.id)) continue;
      const argsObj = (entry.arguments ?? {}) as Record<string, unknown>;
      const placeholder = makePendingToolEntry({
        toolCallId: entry.id,
        name: entry.name,
        argsObject: argsObj,
        createdAt: tsToIso(undefined),
      });
      pendingByCallId.set(entry.id, out.length);
      out.push(placeholder);
      continue;
    }

    if (isAssistant(entry)) {
      const text = pickText(entry.content);
      const thinking = pickThinking(entry.content);
      const toolCalls = pickToolCalls(entry.content);
      const createdAt = tsToIso(entry.timestamp);

      if (text || thinking) {
        out.push(
          makeAssistantTextEntry({
            parentAgentId: entry.parent_id ?? 'root',
            text,
            thinking,
            meta: {
              usage: entry.usage,
              stopReason: entry.stopReason,
              model: entry.model,
              responseId: entry.responseId,
              diagnostics: entry.diagnostics,
              errorMessage: entry.errorMessage,
            },
            createdAt,
            index: i,
          }),
        );
      }

      for (const tc of toolCalls) {
        if (pendingByCallId.has(tc.id)) continue;
        const placeholder = makePendingToolEntry({
          toolCallId: tc.id,
          name: tc.name,
          argsObject: (tc.arguments ?? {}) as Record<string, unknown>,
          createdAt,
        });
        pendingByCallId.set(tc.id, out.length);
        out.push(placeholder);
      }
      continue;
    }

    if (isToolResult(entry)) {
      const idx = pendingByCallId.get(entry.toolCallId);
      if (idx === undefined) {
        // Orphan toolResult — drop silently. (Should not happen with a valid
        // orchestrator log; defensive only.)
        continue;
      }
      const target = out[idx] as CompletedToolCall;
      const text = pickText(entry.content);
      const piDetails = (entry.details ?? {}) as Record<string, unknown>;
      const mergedDetails: Record<string, unknown> = {
        ...piDetails,
        success: !entry.isError,
      };
      target.content = text;
      target.details = mergedDetails;
      // Update created_at to the result's timestamp so per-message sorting
      // reflects when the call completed (closer to legacy behavior where
      // task_result drives created_at).
      target.created_at = tsToIso(entry.timestamp);
      continue;
    }
  }

  return out;
}

/**
 * Sum token usage across the log. Walks three sources (in order of likelihood):
 *   1. AssistantMessage.usage on each assistant turn.
 *   2. ToolResultMessage.details.assistantMessage.usage (sub-agent results).
 *   3. ToolResultMessage.details.usage (custom tools that report their own usage).
 *
 * Used by the chat input's token-limit banner.
 */
export function chatV2TotalTokens(log: ConversationLog): number {
  let total = 0;
  for (const entry of log) {
    if (isAssistant(entry)) {
      total += entry.usage?.totalTokens ?? 0;
      continue;
    }
    if (isToolResult(entry)) {
      const details = entry.details as
        | {
            assistantMessage?: { usage?: { totalTokens?: number } };
            usage?: { totalTokens?: number };
          }
        | undefined;
      total += details?.assistantMessage?.usage?.totalTokens ?? 0;
      total += details?.usage?.totalTokens ?? 0;
    }
  }
  return total;
}
