// emitSyntheticSkillLoads must not re-emit a "Loaded skill X" chip on every turn:
// a skill that already has a skill_load message earlier in the conversation is
// skipped. Auto-injected system skills (e.g. `large_file`) ride the same
// `selected` array every turn while AppState stays large, so without dedup the
// UI shows a duplicate chip per turn.

import { describe, it, expect } from 'vitest';
import { computeSyntheticSkillLoads } from '@/store/chatListener';
import type { AgentSkillSelection } from '@/lib/types';

const NOW = '2026-06-25T00:00:00.000Z';

const loaded = (name: string) => ({
  role: 'autogenerated' as const,
  type: 'skill_load',
  content: { name, source: 'system' },
  created_at: NOW,
});

describe('computeSyntheticSkillLoads', () => {
  it('emits a skill_load message for each newly selected skill', () => {
    const selected: AgentSkillSelection[] = [
      { type: 'system', name: 'large_file' },
      { type: 'user', name: 'my_skill', content: 'x' },
    ];
    const out = computeSyntheticSkillLoads(selected, [], NOW);
    expect(out.map(m => m.content.name)).toEqual(['large_file', 'my_skill']);
    expect(out[0]).toMatchObject({ role: 'autogenerated', type: 'skill_load' });
    expect(out[0].content).toMatchObject({ name: 'large_file', source: 'system' });
  });

  it('skips a skill already loaded earlier in the conversation', () => {
    const selected: AgentSkillSelection[] = [{ type: 'system', name: 'large_file' }];
    const out = computeSyntheticSkillLoads(selected, [loaded('large_file')], NOW);
    expect(out).toEqual([]);
  });

  it('emits only the not-yet-loaded skills when some are already present', () => {
    const selected: AgentSkillSelection[] = [
      { type: 'system', name: 'large_file' },
      { type: 'user', name: 'fresh_skill', content: 'x' },
    ];
    const out = computeSyntheticSkillLoads(selected, [loaded('large_file')], NOW);
    expect(out.map(m => m.content.name)).toEqual(['fresh_skill']);
  });

  it('returns nothing for an empty selection', () => {
    expect(computeSyntheticSkillLoads([], [loaded('large_file')], NOW)).toEqual([]);
  });
});
