/**
 * Story design-theme options for the Clarify `type: 'design'` preset (Story_Design_V2 §6a Layer B).
 *
 * A pure PROJECTION of the theme registry (`lib/data/story/story-themes.ts` — the single source):
 * label/description/value come from each registry entry; imageUrl follows the preview-image
 * convention (`public/story-themes/<name>.png`, generated by `npm run generate-theme-previews`).
 */
import { STORY_THEMES } from '@/lib/data/story/story-themes';

export interface DesignThemeOption {
  /** Short label shown on the option card. */
  label: string;
  /** One-line personality summary — returned to the agent with the pick. */
  description: string;
  /** Preview image rendered on the option card. */
  imageUrl: string;
  /** The theme `name` — what the agent writes into `<theme>…</theme>`. */
  value: string;
}

const DESIGN_THEME_OPTIONS: DesignThemeOption[] = STORY_THEMES.map(t => ({
  value: t.name,
  label: t.label,
  description: t.description,
  imageUrl: `/story-themes/${t.name}.png`,
}));

/** The options the frontend Clarify handler shows for `type: 'design'` (model-passed options are ignored). */
export function getDesignThemeOptions(): DesignThemeOption[] {
  return DESIGN_THEME_OPTIONS;
}
