/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number | null;
export type Name = string;
export type Path = string;
export type Type = "question";
export type Description = string | null;
/**
 * SQL query string, may contain :paramName tokens
 */
export type Query = string;
/**
 * type of the visualization (default is table)
 */
export type VisualizationType =
  | "table"
  | "bar"
  | "line"
  | "scatter"
  | "area"
  | "funnel"
  | "pie"
  | "pivot"
  | "trend"
  | "waterfall"
  | "combo";
/**
 * list of column names in the x axis (for non-pivot chart types)
 */
export type Xcols = string[] | null;
/**
 * list of column names in the y axis (for non-pivot chart types)
 */
export type Ycols = string[] | null;
/**
 * dimension columns for row headers
 */
export type Rows = string[];
/**
 * dimension columns for column headers
 */
export type Columns = string[];
/**
 * column name for the measure
 */
export type Column = string;
/**
 * aggregation function to apply (SUM, AVG, COUNT, MIN, MAX)
 */
export type AggregationFunction = "SUM" | "AVG" | "COUNT" | "MIN" | "MAX";
/**
 * measures with per-value aggregation functions
 */
export type Values = PivotValueConfig[];
/**
 * show row totals column
 */
export type Showrowtotals = boolean | null;
/**
 * show column totals row
 */
export type Showcolumntotals = boolean | null;
/**
 * show heatmap conditional formatting
 */
export type Showheatmap = boolean | null;
/**
 * formulas combining top-level row dimension values
 */
export type Rowformulas = PivotFormula[] | null;
/**
 * display label, e.g. 'YoY Change'
 */
export type Name1 = string;
/**
 * dimension value, e.g. '2024'
 */
export type Operanda = string;
/**
 * dimension value, e.g. '2023'
 */
export type Operandb = string;
/**
 * arithmetic operator: +, -, *, /
 */
export type FormulaOperator = "+" | "-" | "*" | "/";
/**
 * which dimension level to match (0=top-level, 1=second level, etc.). Defaults to 0.
 */
export type Dimensionlevel = number | null;
/**
 * parent dimension values to scope the formula when dimensionLevel > 0, e.g. ['PnL'] means only match within the PnL group
 */
export type Parentvalues = string[] | null;
/**
 * formulas combining top-level column dimension values
 */
export type Columnformulas = PivotFormula[] | null;
/**
 * per-column display formatting keyed by column name. Only set when user asks to rename columns, change decimal places, or change date format. Good defaults are applied automatically.
 */
export type Columnformats = {
  [k: string]: ColumnFormatConfig;
} | null;
/**
 * display name override for the column header
 */
export type Alias = string | null;
/**
 * number of decimal places (0-4) for numeric columns
 */
export type Decimalpoints = number | null;
/**
 * date display format: 'iso', 'us', 'eu', 'short', 'month-year', or 'year'
 */
export type Dateformat = string | null;
/**
 * string to prepend to displayed values (e.g. '$', '€')
 */
export type Prefix = string | null;
/**
 * string to append to displayed values (e.g. '%', ' units', 'k')
 */
export type Suffix = string | null;
/**
 * color overrides mapping series index to color key (e.g. {'0': 'danger', '2': 'warning'}). Only overridden indices are stored.
 */
export type Colors = {
  [k: string]: string;
} | null;
export type Parameters = QuestionParameter[] | null;
export type Name2 = string;
export type ParameterType = "text" | "number" | "date";
export type Label = string | null;
export type Type1 = "question";
export type Id1 = number;
export type Column1 = string;
export type Parametervalues = {
  [k: string]: unknown;
} | null;
/**
 * connection name (empty string if none)
 */
export type DatabaseName = string;
export type References = QuestionReference[] | null;
export type Id2 = number;
export type Alias1 = string;
export type References1 = number[] | null;
export type Id3 = number | null;
export type Name3 = string;
export type Path1 = string;
export type Type2 = "dashboard";
export type Description1 = string | null;
export type Type3 = "question";
export type Id4 = number;
export type Type4 = "text" | "image" | "divider";
export type Id5 = string | null;
export type Content = string | null;
/**
 * ordered list of questions in the dashboard
 */
export type Assets = (FileReference | InlineAsset)[];
export type Columns1 = number | null;
export type Items = DashboardLayoutItem[] | null;
export type Id6 = number;
export type X = number;
export type Y = number;
/**
 * width in grid units (min 2)
 */
export type W = number;
/**
 * height in grid units (min 2)
 */
export type H = number;
export type Parametervalues1 = {
  [k: string]: unknown;
} | null;
export type References2 = number[] | null;

export interface AtlasQuestionFile {
  id?: Id;
  name: Name;
  path: Path;
  type: Type;
  content: QuestionContent;
  references?: References1;
}
export interface QuestionContent {
  description?: Description;
  query: Query;
  vizSettings: VizSettings;
  parameters?: Parameters;
  parameterValues?: Parametervalues;
  database_name: DatabaseName;
  references?: References;
}
/**
 * visualization settings
 */
export interface VizSettings {
  type: VisualizationType;
  xCols?: Xcols;
  yCols?: Ycols;
  /**
   * pivot table configuration (only used when type is 'pivot')
   */
  pivotConfig?: PivotConfig | null;
  columnFormats?: Columnformats;
  colors?: Colors;
}
/**
 * Configuration for pivot table visualization.
 */
export interface PivotConfig {
  rows: Rows;
  columns: Columns;
  values: Values;
  showRowTotals?: Showrowtotals;
  showColumnTotals?: Showcolumntotals;
  showHeatmap?: Showheatmap;
  rowFormulas?: Rowformulas;
  columnFormulas?: Columnformulas;
}
/**
 * A measure column with its aggregation function.
 */
export interface PivotValueConfig {
  column: Column;
  aggFunction?: AggregationFunction;
}
/**
 * A derived row/column computed from two dimension values at a given level.
 */
export interface PivotFormula {
  name: Name1;
  operandA: Operanda;
  operandB: Operandb;
  operator: FormulaOperator;
  dimensionLevel?: Dimensionlevel;
  parentValues?: Parentvalues;
}
/**
 * Per-column display formatting. Only set when the user explicitly asks to change formatting.
 */
export interface ColumnFormatConfig {
  alias?: Alias;
  decimalPoints?: Decimalpoints;
  dateFormat?: Dateformat;
  prefix?: Prefix;
  suffix?: Suffix;
}
export interface QuestionParameter {
  name: Name2;
  type: ParameterType;
  label?: Label;
  source?: ParameterSource | null;
}
/**
 * Reference to another question whose output drives a parameter's dropdown values.
 */
export interface ParameterSource {
  type: Type1;
  id: Id1;
  column: Column1;
}
/**
 * Composed question reference — lets this query use @alias as a CTE.
 */
export interface QuestionReference {
  id: Id2;
  alias: Alias1;
}
export interface AtlasDashboardFile {
  id?: Id3;
  name: Name3;
  path: Path1;
  type: Type2;
  content: DashboardContent;
  references?: References2;
}
export interface DashboardContent {
  description?: Description1;
  assets: Assets;
  layout?: DashboardLayout | null;
  parameterValues?: Parametervalues1;
}
/**
 * A reference to another question embedded in the dashboard.
 */
export interface FileReference {
  type: Type3;
  id: Id4;
}
/**
 * Inline content block (text, image, divider) — no external file.
 */
export interface InlineAsset {
  type: Type4;
  id?: Id5;
  content?: Content;
}
export interface DashboardLayout {
  columns?: Columns1;
  items?: Items;
}
export interface DashboardLayoutItem {
  id: Id6;
  x: X;
  y: Y;
  w: W;
  h: H;
}
