/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number | null;
export type Name = string;
export type Path = string;
export type Type = "question";
export type Description = string | null;
/**
 * SQL query string, may contain :paramName tokens
 */
export type Query = string;
/**
 * type of the visualization (default is table)
 */
export type VisualizationType =
  | "table"
  | "bar"
  | "line"
  | "scatter"
  | "area"
  | "funnel"
  | "pie"
  | "pivot"
  | "trend"
  | "waterfall"
  | "combo"
  | "radar";
/**
 * list of column names in the x axis (for non-pivot chart types)
 */
export type Xcols = string[] | null;
/**
 * list of column names in the y axis (for non-pivot chart types). When dualAxis is enabled in axisConfig, these are the left-axis columns.
 */
export type Ycols = string[] | null;
/**
 * list of column names for the right Y axis (only used when axisConfig.dualAxis is true)
 */
export type Yrightcols = string[] | null;
/**
 * additional columns to show in chart tooltips without changing grouping or series structure
 */
export type Tooltipcols = string[] | null;
/**
 * dimension columns for row headers
 */
export type Rows = string[];
/**
 * dimension columns for column headers
 */
export type Columns = string[];
/**
 * column name for the measure
 */
export type Column = string;
/**
 * aggregation function to apply (SUM, AVG, COUNT, MIN, MAX)
 */
export type AggregationFunction = "SUM" | "AVG" | "COUNT" | "MIN" | "MAX";
/**
 * measures with per-value aggregation functions
 */
export type Values = PivotValueConfig[];
/**
 * show row totals column
 */
export type Showrowtotals = boolean | null;
/**
 * show column totals row
 */
export type Showcolumntotals = boolean | null;
/**
 * show heatmap conditional formatting
 */
export type Showheatmap = boolean | null;
/**
 * compact heatmap mode: hides cell values, shows only colored squares with tooltips, and uses smaller cells — like a GitHub contribution graph
 */
export type Compact = boolean | null;
/**
 * heatmap color scale: 'red-yellow-green' (default), 'green' (single-hue like GitHub), 'blue' (single-hue blue)
 */
export type Heatmapscale = string | null;
/**
 * formulas combining top-level row dimension values
 */
export type Rowformulas = PivotFormula[] | null;
/**
 * display label, e.g. 'YoY Change'
 */
export type Name1 = string;
/**
 * dimension value, e.g. '2024'
 */
export type Operanda = string;
/**
 * dimension value, e.g. '2023'
 */
export type Operandb = string;
/**
 * arithmetic operator: +, -, *, /
 */
export type FormulaOperator = "+" | "-" | "*" | "/";
/**
 * which dimension level to match (0=top-level, 1=second level, etc.). Defaults to 0.
 */
export type Dimensionlevel = number | null;
/**
 * parent dimension values to scope the formula when dimensionLevel > 0, e.g. ['PnL'] means only match within the PnL group
 */
export type Parentvalues = string[] | null;
/**
 * formulas combining top-level column dimension values
 */
export type Columnformulas = PivotFormula[] | null;
/**
 * per-column display formatting keyed by column name. Only set when user asks to rename columns, change decimal places, or change date format. Good defaults are applied automatically.
 */
export type Columnformats = {
  [k: string]: ColumnFormatConfig;
} | null;
/**
 * display name override for the column header
 */
export type Alias = string | null;
/**
 * number of decimal places (0-4) for numeric columns
 */
export type Decimalpoints = number | null;
/**
 * date display format: 'iso', 'us', 'eu', 'short', 'month-year', or 'year'
 */
export type Dateformat = string | null;
/**
 * string to prepend to displayed values (e.g. '$', '€')
 */
export type Prefix = string | null;
/**
 * string to append to displayed values (e.g. '%', ' units', 'k')
 */
export type Suffix = string | null;
/**
 * color overrides mapping series index to color key (e.g. {'0': 'danger', '2': 'warning'}).
 */
export type Colors = {
  [k: string]: string;
} | null;
/**
 * series opacity from 0.1 to 1.0
 */
export type Opacity = number | null;
/**
 * point marker size for charts that render markers, such as scatter and line
 */
export type Markersize = number | null;
/**
 * whether bar and area series should be stacked. Defaults to true for those chart types.
 */
export type Stacked = boolean | null;
/**
 * annotations for cartesian charts. Each annotation specifies x, series, and text.
 */
export type Annotations = ChartAnnotation[] | null;
/**
 * X-axis value to anchor the annotation to
 */
export type X = string | number;
/**
 * series name to anchor the annotation to
 */
export type Series = string | null;
/**
 * annotation label text
 */
export type Text = string;
/**
 * deprecated legacy color overrides. Use styleConfig.colors instead.
 */
export type Colors1 = {
  [k: string]: string;
} | null;
export type AxisScale = "linear" | "log";
/**
 * explicit X-axis minimum value
 */
export type Xmin = number | null;
/**
 * explicit X-axis maximum value
 */
export type Xmax = number | null;
/**
 * explicit Y-axis minimum value
 */
export type Ymin = number | null;
/**
 * explicit Y-axis maximum value
 */
export type Ymax = number | null;
/**
 * optional Y-axis title override for charts with a single Y axis
 */
export type Ytitle = string | null;
/**
 * enable dual Y-axis mode. When true, yRightCols in VizSettings determines which columns go on the right axis.
 */
export type Dualaxis = boolean | null;
export type Parameters = QuestionParameter[] | null;
export type Name2 = string;
export type ParameterType = "text" | "number" | "date";
export type Label = string | null;
export type Source = QuestionParameterSource | SqlParameterSource | null;
export type Type1 = "question";
export type Id1 = number;
export type Column1 = string;
export type Type2 = "sql";
export type Query1 = string;
export type Parametervalues = {
  [k: string]: unknown;
} | null;
/**
 * connection name (empty string if none)
 */
export type ConnectionName = string;
export type References = QuestionReference[] | null;
export type Id2 = number;
export type Alias1 = string;
export type References1 = number[] | null;
export type Id3 = number | null;
export type Name3 = string;
export type Path1 = string;
export type Type3 = "dashboard";
export type Description1 = string | null;
export type Type4 = "question";
export type Id4 = number;
export type Type5 = "text" | "image" | "divider";
export type Id5 = string | null;
export type Content = string | null;
/**
 * ordered list of questions in the dashboard
 */
export type Assets = (FileReference | InlineAsset)[];
export type Columns1 = number | null;
export type Items = DashboardLayoutItem[] | null;
export type Id6 = number | string;
export type X1 = number;
export type Y = number;
/**
 * width in grid units (min 2)
 */
export type W = number;
/**
 * height in grid units (min 1)
 */
export type H = number;
export type Parametervalues1 = {
  [k: string]: unknown;
} | null;
export type References2 = number[] | null;

export interface AtlasQuestionFile {
  id?: Id;
  name: Name;
  path: Path;
  type: Type;
  content: QuestionContent;
  references?: References1;
}
export interface QuestionContent {
  description?: Description;
  query: Query;
  vizSettings: VizSettings;
  parameters?: Parameters;
  parameterValues?: Parametervalues;
  connection_name: ConnectionName;
  references?: References;
}
/**
 * visualization settings
 */
export interface VizSettings {
  type: VisualizationType;
  xCols?: Xcols;
  yCols?: Ycols;
  yRightCols?: Yrightcols;
  tooltipCols?: Tooltipcols;
  /**
   * pivot table configuration (only used when type is 'pivot')
   */
  pivotConfig?: PivotConfig | null;
  columnFormats?: Columnformats;
  /**
   * shared visual styling for the chart, such as colors, opacity, and marker size.
   */
  styleConfig?: VisualizationStyleConfig | null;
  annotations?: Annotations;
  colors?: Colors1;
  /**
   * axis configuration for scale type (linear or log). Only set when user explicitly requests log scale.
   */
  axisConfig?: AxisConfig | null;
}
/**
 * Configuration for pivot table visualization.
 */
export interface PivotConfig {
  rows: Rows;
  columns: Columns;
  values: Values;
  showRowTotals?: Showrowtotals;
  showColumnTotals?: Showcolumntotals;
  showHeatmap?: Showheatmap;
  compact?: Compact;
  heatmapScale?: Heatmapscale;
  rowFormulas?: Rowformulas;
  columnFormulas?: Columnformulas;
}
/**
 * A measure column with its aggregation function.
 */
export interface PivotValueConfig {
  column: Column;
  aggFunction?: AggregationFunction;
}
/**
 * A derived row/column computed from two dimension values at a given level.
 */
export interface PivotFormula {
  name: Name1;
  operandA: Operanda;
  operandB: Operandb;
  operator: FormulaOperator;
  dimensionLevel?: Dimensionlevel;
  parentValues?: Parentvalues;
}
/**
 * Per-column display formatting. Only set when the user explicitly asks to change formatting.
 */
export interface ColumnFormatConfig {
  alias?: Alias;
  decimalPoints?: Decimalpoints;
  dateFormat?: Dateformat;
  prefix?: Prefix;
  suffix?: Suffix;
}
/**
 * Shared visual styling controls for charts.
 */
export interface VisualizationStyleConfig {
  colors?: Colors;
  opacity?: Opacity;
  markerSize?: Markersize;
  stacked?: Stacked;
}
/**
 * A chart annotation anchored to an existing chart x value and series with a short text label.
 */
export interface ChartAnnotation {
  x: X;
  series?: Series;
  text: Text;
}
/**
 * Per-axis configuration for scale type and range.
 */
export interface AxisConfig {
  /**
   * X-axis scale type: 'linear' (default) or 'log'
   */
  xScale?: AxisScale | null;
  /**
   * Y-axis scale type: 'linear' (default) or 'log'
   */
  yScale?: AxisScale | null;
  xMin?: Xmin;
  xMax?: Xmax;
  yMin?: Ymin;
  yMax?: Ymax;
  yTitle?: Ytitle;
  dualAxis?: Dualaxis;
}
export interface QuestionParameter {
  name: Name2;
  type: ParameterType;
  label?: Label;
  source?: Source;
}
/**
 * Reference to another question whose output drives a parameter's dropdown values.
 */
export interface QuestionParameterSource {
  type: Type1;
  id: Id1;
  column: Column1;
}
/**
 * Inline SQL query whose first column drives a parameter's dropdown values.
 */
export interface SqlParameterSource {
  type: Type2;
  query: Query1;
}
/**
 * Composed question reference — lets this query use @alias as a CTE.
 */
export interface QuestionReference {
  id: Id2;
  alias: Alias1;
}
export interface AtlasDashboardFile {
  id?: Id3;
  name: Name3;
  path: Path1;
  type: Type3;
  content: DashboardContent;
  references?: References2;
}
export interface DashboardContent {
  description?: Description1;
  assets: Assets;
  layout?: DashboardLayout | null;
  parameterValues?: Parametervalues1;
}
/**
 * A reference to another question embedded in the dashboard.
 */
export interface FileReference {
  type: Type4;
  id: Id4;
}
/**
 * Inline content block (text, image, divider) — no external file.
 */
export interface InlineAsset {
  type: Type5;
  id?: Id5;
  content?: Content;
}
export interface DashboardLayout {
  columns?: Columns1;
  items?: Items;
}
export interface DashboardLayoutItem {
  id: Id6;
  x: X1;
  y: Y;
  w: W;
  h: H;
}
