/**
 * QueryBuilderRoot
 * Entry point that handles both simple and compound (UNION) queries.
 * Dispatches to QueryBuilder or CompoundQueryBuilder based on IR type.
 */

'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { Box, HStack, Spinner, Text, VStack } from '@chakra-ui/react';
import type { AnyQueryIR, QueryIR, CompoundQueryIR } from '@/lib/types';
import { isCompoundQueryIR } from '@/lib/types';
import { CompletionsAPI } from '@/lib/data/completions/completions';
import { QueryBuilder } from './QueryBuilder';
import { CompoundQueryBuilder } from './CompoundQueryBuilder';
import type { QuestionOption } from '@/lib/hooks/useAvailableQuestions';

interface QueryBuilderRootProps {
  databaseName: string;
  sql: string;
  onSqlChange: (sql: string) => void;
  onExecute?: () => void;
  isExecuting?: boolean;
  availableQuestions?: QuestionOption[];
}

export function QueryBuilderRoot({
  databaseName,
  sql,
  onSqlChange,
  onExecute,
  isExecuting = false,
  availableQuestions = [],
}: QueryBuilderRootProps) {
  const [mode, setMode] = useState<'simple' | 'compound' | 'loading' | 'error'>('loading');
  const [compoundIR, setCompoundIR] = useState<CompoundQueryIR | null>(null);
  const [error, setError] = useState<string | null>(null);
  const lastSqlRef = useRef<string>('');
  const lastGeneratedSqlRef = useRef<string>('');

  // Detect whether the SQL is a compound query on initial load and when SQL changes externally
  useEffect(() => {
    // Skip if SQL was generated by us (to avoid loops)
    if (sql === lastGeneratedSqlRef.current) return;
    if (sql === lastSqlRef.current && mode !== 'loading') return;
    lastSqlRef.current = sql;

    async function detectMode() {
      if (!sql.trim()) {
        setMode('simple');
        return;
      }

      try {
        const result = await CompletionsAPI.sqlToIR({ sql });
        if (result.success && result.ir) {
          if (isCompoundQueryIR(result.ir)) {
            setCompoundIR(result.ir);
            setMode('compound');
          } else {
            setCompoundIR(null);
            setMode('simple');
          }
          setError(null);
        } else {
          // IR parse failed — fall back to simple mode (QueryBuilder handles its own errors)
          setCompoundIR(null);
          setMode('simple');
        }
      } catch {
        setCompoundIR(null);
        setMode('simple');
      }
    }

    detectMode();
  }, [sql]);

  // Handle converting a simple query to compound
  const handleConvertToCompound = useCallback(async () => {
    // Parse current SQL to get the QueryIR
    try {
      const result = await CompletionsAPI.sqlToIR({ sql });
      if (result.success && result.ir && !isCompoundQueryIR(result.ir)) {
        const currentQuery = result.ir as QueryIR;
        const emptyQuery: QueryIR = {
          type: 'simple',
          version: 1,
          select: [],
          from: { table: '' },
        };
        const compound: CompoundQueryIR = {
          type: 'compound',
          version: 1,
          queries: [currentQuery, emptyQuery],
          operators: ['UNION ALL'],
        };
        setCompoundIR(compound);
        setMode('compound');

        // Generate SQL for the compound IR
        const sqlResult = await CompletionsAPI.irToSql({ ir: compound });
        if (sqlResult.success && sqlResult.sql) {
          lastGeneratedSqlRef.current = sqlResult.sql;
          onSqlChange(sqlResult.sql);
        }
      }
    } catch (err) {
      console.error('[QueryBuilderRoot] Failed to convert to compound:', err);
    }
  }, [sql, onSqlChange]);

  // Handle compound IR changes
  const handleCompoundIRChange = useCallback(
    async (newIR: CompoundQueryIR) => {
      setCompoundIR(newIR);

      // If reduced to 1 query, convert back to simple
      if (newIR.queries.length <= 1) {
        setMode('simple');
        setCompoundIR(null);
        if (newIR.queries.length === 1) {
          const sqlResult = await CompletionsAPI.irToSql({ ir: newIR.queries[0] });
          if (sqlResult.success && sqlResult.sql) {
            lastGeneratedSqlRef.current = sqlResult.sql;
            onSqlChange(sqlResult.sql);
          }
        }
        return;
      }

      // Generate SQL from updated compound IR
      try {
        const result = await CompletionsAPI.irToSql({ ir: newIR });
        if (result.success && result.sql) {
          lastGeneratedSqlRef.current = result.sql;
          lastSqlRef.current = result.sql;
          onSqlChange(result.sql);
        }
      } catch (err) {
        console.error('[QueryBuilderRoot] Failed to generate compound SQL:', err);
      }
    },
    [onSqlChange]
  );

  if (mode === 'loading') {
    return (
      <Box p={4}>
        <HStack gap={3}>
          <Spinner size="sm" color="blue.400" />
          <Text fontSize="sm" color="fg.muted">Loading query builder...</Text>
        </HStack>
      </Box>
    );
  }

  if (mode === 'compound' && compoundIR) {
    return (
      <CompoundQueryBuilder
        databaseName={databaseName}
        ir={compoundIR}
        onIRChange={handleCompoundIRChange}
        onExecute={onExecute}
        isExecuting={isExecuting}
        availableQuestions={availableQuestions}
      />
    );
  }

  // Simple mode — pass through to regular QueryBuilder
  return (
    <QueryBuilder
      databaseName={databaseName}
      sql={sql}
      onSqlChange={(newSql) => {
        lastGeneratedSqlRef.current = newSql;
        onSqlChange(newSql);
      }}
      onExecute={onExecute}
      isExecuting={isExecuting}
      availableQuestions={availableQuestions}
      onConvertToCompound={handleConvertToCompound}
    />
  );
}
